### ISSUE TITLE
Remove oldest unused tab rather than leftmost tab?

### ISSUE THREAD

**Issue by gingerbeardman** [diffsky/tabalot#1]
It'd be cool if this could track a "last updated" timestamp on each tab and remove the tab that was last used, rather than the leftmost one?

This is how Mobile Safari used to get rid of tabs (when it enforced a limit)

**Comment by matthewhadley** [comment]
Yeah, that's a great idea.

**Comment by matthewhadley** [comment]
This should get published as version `1.0.0` in the next hour or so @gingerbeardman. Thanks for the suggestions!

**Comment by matthewhadley** [comment]
aaaand I just published `1.1.0`  because I think I introduced a bug around closing too many tabs at once.

**Comment by matthewhadley** [comment]
now `1.2.0`

**Comment by gingerbeardman** [comment]
Nicely done!
